fix: add net8 and net7 support
stylianosnicoletti/dotnet-certificate-tool pull request #31
Opened 2023-11-09 10:41 UTC by elonmallin

Hi, I'd like to add .net8 and .net7 support to this great tool. This PR is the same as the last merged PR which added .net6.

What do you think about merging this when .net8 is released on 2023-11-14?

2023-11-10 23:13 UTC, elonmallin commented
Hi @starcraft66 @Gcaya @asimmon @decarufe and sorry to tag you like this but this tool seems to be heavily used ([downloaded 700 times per day](https://www.nuget.org/packages/dotnet-certificate-tool)) even though it's unlisted. It also has 2 published spinoffs to add support for .NET7.

Is there any interest from Workleap to relist this nuget or give the ownership to me or someone else to support it?

2023-11-16 11:40 UTC, dradovic commented
@elonmallin Thanks Elon for you contribution. I did the .NET 7 upgrade last year. Unfortunately, nobody from the original owners of this repo ever replied so far.

Again, as I need it in my CI environment, I've pushed a version to nuget.org. Here's what I did:

1. Cloned your repo from `https://github.com/elonmallin/dotnet-certificate-tool.git`
2. Adjusted package ID to `<PackageId>dotnet-certificate-tool-net8</PackageId>` to not have a conflict on nuget.org
3. `dotnet build -c Release`
4. `dotnet pack -c Release GSoft.CertificateTool.csproj`
5. Uploaded to nuget.org

And here it is: https://www.nuget.org/packages/dotnet-certificate-tool-net8/1.0.0

2023-11-16 17:29 UTC, elonmallin commented
Thanks @dradovic !

Are you interested in maintaining your version? Might be nice with a non framework specific name in that case and making a public repo for it :)

2023-11-17 08:13 UTC, dradovic commented
I'm not necessarily keen to become a maintainer of this project as I'm not acquainted with its actual logic. I still hope that somebody of the original maintainers will step up or somebody else (you? ;).

But who knows. If we bump our heads against a .NET upgrade that requires more than just adjusting some .NET tags, we need a new maintained public repo.

2024-01-11 08:44 UTC, SoyDiego commented
@gsoft-inc @yohanb will you approve this PR?

Thanks!

2024-01-11 08:46 UTC, SoyDiego commented
@gsoft-inc @yohanb @patricklafrance @decarufe will you approve this PR?

Thanks!

2024-01-11 14:18 UTC, yohanb approved these changes

2024-02-15 19:56 UTC, stylianosnicoletti commented
@elonmallin can you please merge the PR

2024-02-19 15:14 UTC, stylianosnicoletti requested changes

2024-02-19 15:14 UTC, stylianosnicoletti commented on docker-example/Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk:8.0.100-bullseye-slim-amd64 as build-env
use latest '8.0.201-bookworm-slim-amd64'

2024-02-19 15:14 UTC, stylianosnicoletti commented on docker-example/Dockerfile
> +FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-bullseye-slim-amd64
use latest '8.0.201-bookworm-slim-amd64'

2024-02-20 10:17 UTC, stylianosnicoletti commented
Hi @elonmallin the docker image used in your PR seems to be wrong/outdated. Can you please change it to the one suggested above?

2024-02-20 10:44 UTC, williamiss commented
This is a widely used tool, are there plans to merge this PR?

2024-02-20 10:54 UTC, daphneSot commented
Hello, can you merge this PR as we need it to upgrade our environments?

2024-02-20 20:48 UTC, decarufe commented
See: [Seeking New Maintainers for dotnet-certificat-tool](https://github.com/gsoft-inc/dotnet-certificate-tool/issues/34)

2024-02-29 18:56 UTC, stylianosnicoletti approved these changes

2024-02-29 18:56 UTC, merged